services:
  frontend:
    container_name: hotels_frontend
    image: node:20-alpine
    working_dir: /hotels_frontend
    volumes:
      - .:/hotels_frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - 9000:9000
