export enum AmenitiesEnum {
  wifi = 'WI_FI',
  restaurant = 'RESTAURANT',
  room_service = 'ROOM_SERVICE',
  meeting_room = 'MEETING_ROOM',
  local_laundry_service = 'LAUNDRY',
  bakery_dining = 'BREAKFAST',
  local_parking = 'PARKING',
  fitness_center = 'FITNESS_CENTER',
  pool = 'POOL',
  self_improvement = 'SPA',
  hot_tub = 'STEAM_ROOM',
  pets = 'PETS',
  sports_bar = 'PUB',
  ac_unit = 'AIR_CONDITIONING',
  lock = 'SAFE',
  tv = 'ROOM_TV',
  timer = 'RECEPTION_24_HOURS',
  vertical_shades = 'STAGE',
  vertical_shades_closed = 'AUDITORIUM',
  spa = 'MASSAGE',
  mood = 'PLAY_GROUND',
  cases = 'TRANSFER',
}
